if GetLocale() ~= "frFR" then return end
local _, addon = ...
local L = addon.L

-- ==================== Callbacks ==================== --
L.StrCbErrUsage = "Utilisation: KRT:RegisterCallback(event, callbacks)"
L.StrCbErrExec = "Erreur lors de l'exécution de %s pour l'événement %s: %s"

-- ==================== General Buttons ==================== --
L.BtnConfig       = "Config"
L.BtnConfigure    = "Configurer"
L.BtnConfirm      = "Confirmer"
L.BtnDefaults     = "Défaut"
L.BtnEdit         = "Modif."
L.BtnOK           = "OK"
L.BtnStop         = "Arrêter"
L.BtnResume       = "Reprendre"

-- ==================== Minimap Button ==================== --
L.StrMinimapLClick = "|cffffd700Click-gauche|r pour accéder au menu"
L.StrMinimapRClick = "|cffffd700Clic-droit|r pour configurer"
L.StrMinimapSClick = "|cffffd700Shift+Clic|r pour déplacer"
L.StrMinimapAClick = "|cffffd700Alt+Clic|r pour déplacer librement"
L.StrLootHistory   = "Historique"
L.StrRaidWarnings  = "Avertissements"
L.StrLFMSpam       = "LFM Spam"
L.StrMSChanges     = "Changement MS"
L.StrLootBans      = "Bans de loot"
L.StrSpamBans      = "Annoncer les bans"
L.StrClearIcons    = "Retirer les icônes"

-- ==================== Loot Master Frame ==================== --
L.BtnSelectItem            = "Sélectionner"
L.BtnRemoveItem            = "Retirer"
L.BtnSpamLoot              = "Annoncer"
L.BtnMS                    = "MS"
L.BtnOS                    = "OS"
L.BtnFree                  = "Libre"
L.BtnRoll                  = "Rouler"
L.BtnCountdown             = "C. à rebours"
L.BtnAward                 = "Attribuer"
L.BtnHold                  = "Tenir"
L.BtnBank                  = "Garder"
L.BtnDisenchant            = "DE"
L.StrNoItemSelected        = "Aucun item sélectionné"
L.StrRoll                  = "Rouler"
L.ChatSpamLoot             = "Butin du boss:"
L.ChatReadyCheck           = "Appel avant de rouler des items!"
L.ChatRollMS               = "Rouler pour MS on: %s"
L.ChatRollOS               = "Rouler pour OS on: %s"
L.ChatRollFree             = "Rouler: %s"
L.ChatRollMSMultipleHigh   = "Rouler pour MS: %s. Top %s gagnent"
L.ChatRollOSMultipleHigh   = "Rouler pour OS: %s. Top %s gagnent"
L.ChatRollFreeMultipleHigh = "Rouler: %s. Top %s gagnent"
L.ChatRollMSMultipleLow    = "Rouler pour MS: %s. Derniers %s gagnent"
L.ChatRollOSMultipleLow    = "Rouler pour OS: %s. Derniers %s gagnent"
L.ChatRollFreeMultipleLow  = "Rouler: %s. Derniers %s gagnent"
L.ChatCountdownTic         = "Fin de roulement dans %d sec"
L.ChatCountdownEnd         = "Fin de roulement!"
L.ChatCountdownBlock       = "Tous les roulements après le compte à rebours sont ignorés!"
L.ChatAward                = "Félicitations! %s gagne %s"
L.ChatTrade                = "Félicitations! {triangle} %s ! Veuillez échanger avec {star} %s"
L.ChatTradeMutiple         = "Les gagnants sont: %s, veuillez échanger avec {star} %s"
L.ChatPlayerRolled         = "%s a eu %s"
L.ChatHold                 = "%s gardera %s pour plus tard"
L.ChatBank                 = "%s gardera %s (pour la banque)"
L.ChatDisenchant           = "%s sera désenchanté par %s"
L.ChatNoneRolledHold       = "Personne ne veut %s, %s le garde"
L.ChatNoneRolledBank       = "Personne ne veut %s, %s le garde pour la banque"
L.ChatNoneRolledDisenchant = "Persone ne veut %s, il sera désenchanté par %s"
L.ChatOnlyRollOnce         = "KRT > Vous ne pouvez rouler qu'une fois!"
L.WhisperHoldTrade         = "KRT > Veuillez échanger avec moi pour garder %s"
L.WhisperBankTrade         = "KRT > Veuillez échanger avec moi pour garder %s (banque)"
L.WhisperDisenchantTrade   = "KRT > Veuillez échanger avec moi pour désenchanter %s"
L.WhisperHoldAssign        = "KRT > Vous venez de recevoir %s. Il sera rouler plus tard."
L.WhisperBankAssign        = "KRT > Vous venez de recevoir %s (réservé pour la banque)"
L.WhisperDisenchantAssign  = "KRT > Vous venez de recevoir %s. Veuillez le désenchanter."
L.ErrScreenReminder        = "Veuillez prendre une capture d'écran avant d'échanger!"
L.ErrItemStack             = "Vous avez une pile de %s, il est préférable de le scinder d'abord!"
L.ErrCannotFindItem        = "Impossible de trouver l'item: %s"
L.ErrCannotFindPlayer      = "Impossible de trouver le joueur: %s"

-- ==================== Configuration Frame ==================== --
L.StrConfigSortAscending        = "Ordre croissant des scores"
L.StrConfigUseRaidWarning       ="Utiliser les avertissements de raid"
L.StrConfigAnnounceOnWin        = "Annoncer les gagnants des items"
L.StrConfigAnnounceOnHold       = "Annoncer les items gardés pour plus tard"
L.StrConfigAnnounceOnBank       = "Annoncer les items réservés (banque)"
L.StrConfigAnnounceOnDisenchant = "Annoncer les items désenchantés"
L.StrConfigLootWhisper          = "Envoyer un messages au détenteur des items"
L.StrConfigCountdownRollsBlock  = "Tout ignorer après le compte à rebous"
L.StrConfigScreenReminder       = "Rappel de capture avant d'échanger un item"
L.StrConfigIgnoreStacks         = "Autoriser l'échange des piles"
L.StrConfigShowTooltips         = "Afficher les info-bulles"
L.StrConfigMinimapButton        = "Afficher le bouton de la mini-carte"
L.StrConfigCountdownDuration    = "Durée du compte à rebours"
L.StrConfigAbout                = "Réalisé avec amour bar |cfff58cbaKader|r B\n|cffffffffhttps://github.com/bkader|r\nhttps://discord.gg/a8z5CyS3eW"

-- ==================== Raid Warnings Frame ==================== --
L.StrMessage            = "Message"
L.StrWarningsHelp       = "Astuces:"
L.StrWarningsHelp       = "- |cffffd700Left-Click|r to select a warning, click again to cancel selection.\n- |cffffd700Ctrl-Click|r for a quick raid warning.\n- When you select a warning, you can either |cffffd700Edit|r it, |cffffd700Delete|r it or |cffffd700Announce|r it using the provided buttons."
L.StrWarningsError      = "Seul le message est requis! Toutefois, il est recommandé de nommer vos messages afin de vous y retrouver."
L.StrCmdWarningAnnounce = "annonce l'avertissement spéficié"

-- ==================== MS Changes Frame ==================== --
L.StrChanges             = "Changement MS"
L.StrChangesDemand       = "Veuillez m'envoyer vos changements de MS avant de commencer!"
L.StrChangesAnnounce     = "Changement MS: "
L.StrChangesAnnounceOne  = "%s roule %s"
L.StrChangesAnnounceNone = "Aucun changement MS reçu!"
L.BtnClear               = "Effacer"
L.BtnDemand              = "Demander"
L.BtnAnnounce            = "Annoncer"
L.ErrChangesNoPlayer     = "Le nom est requis. Un changement vide retirera le joueur de la liste."

-- ==================== LFM Spam Frame ==================== --
L.StrSpammer            = "LFM Spam"
L.StrSpammerCompStr     = "Composition"
L.StrSpammerMessageStr  = "Message"
L.StrSpammerPreviewStr  = "Aperçu"
L.StrSpammerErrLength   = "Votre message LFM est trop long."
L.StrSpammerDurationHelp = "Il est recommendé d'utiliser au moins 60 secondes pour un server mute."
L.StrSpammerMessageHelp1 = "Ceci sera joint au message générer."
L.StrSpammerMessageHelp2 = "Vous pouvez utiliser |cffffd700{ID}|r pour inclure un haut-fait."
L.StrSpammerMessageHelp3 = "Vous pouvez trouver l'|cffffd700ID|r en utilisant la commande: \n|cffffd700/krt ach [link]|r."

-- ==================== Logger Frame ==================== --
L.StrDate     = "Date"
L.StrSize     = "Taille"
L.StrTime     = "Temps"
L.StrItem     = "Item"
L.StrSource   = "Source"
L.StrWinner   = "Gagnant"
L.StrType     = "Type"
L.StrLoading  = "Chargement..."
L.BtnExport   = "Exporter"

-- Raids List:
L.StrRaidsList = "Raids"
L.StrSetCurrent = "R. Actuel"
L.StrConfirmDeleteRaid = "Êtes-vous sûr de vouloir supprimer ce raid?"
L.StrRaidCurrentTitle = "Info de doublons"
L.StrRaidsCurrentHelp = "Il est parfois possible de remarque des doublons. Si cela arrive, veuillez rendre le raid sélectionné comme actuel et supprimer tous les doublons."
L.ErrCannotDeleteRaid = "Impossible de supprimer le raid actuel."
L.ErrCannotSetCurrentRaidSize = "Impossible d'utiliser un raid de différente difficulté comme raid actuel."
L.ErrCannotSetCurrentRaidReset = "Impossible d'utiliser un raid expiré comme raid actuel."
L.StrNewRaidSessionChange = "Zone or taille de raid changés. Création d'un nouveau raid."

-- Boss List:
L.StrBosses = "Bosses"
L.StrTrashMob = "Trash Mob"
L.StrConfirmDeleteBoss = "Êtes-vous sûr de vouloir supprimer ce boss?"

-- Raid Attendees:
L.StrRaidAttendees = "Participants au raid"
L.StrJoin = "Inscrip."
L.StrLeave = "Départ"
L.StrConfirmDeleteAttendee = "Êtes-vous sûr de vouloir retirer ce joueur du raid?"

L.StrBossAttendees = "Participants au boss"
L.StrPlayers       = "Joueurs"

-- Raid loot list:
L.StrRaidLoot = "Butin de raid"
L.StrUnknown = "Inconnu"
L.StrConfirmDeleteItem = "Êtes-vous sûr de vouloir supprimer cet item de l'historique?"
L.StrEditItemLooter = "Changer le gagnant"
L.StrEditItemLooterHelp = "Entrez le nom du gagnant:"
L.StrEditItemRollType = "Changer le type"
L.StrEditItemRollTypeHelp = "1=MS, 2=OS, 3=Libre, 4=Banque, 5=DE, 6=Garder, 7=DKP"
L.StrEditItemRollValue = "Changer le score"
L.StrEditItemRollValueHelp = "Entrez la valeur du score ou le DKP:"

-- Add/Edit Boss:
L.StrAddBoss = "Nouveau Boss"
L.StrEditBoss = "Modifier Boss"
L.StrBossNameHelp = "Laisser vide pour |cffffd700Trash Mob|r."
L.StrBossDifficultyHelp = "\"|cffffd700N|r\" pour normal ou \"|cffffd700H|r\" for héroïque."
L.StrBossTimeHelp = "Format accepté: |cffffd700DD/MM/YYY HH:MM|r."
L.ErrBossDifficulty = "Veuillez entrer une difficulté valide: N or H"
L.ErrBossTime = "Veuillez entrer un temps valide: HH:MM"

-- Add/Delete Players/Boss  Attendees:
L.StrAddPlayer = "Nouveau Joueur"
L.ErrAttendeesInvalidName = "Le nom de joueur est invalide ou le joueur n'était pas dans le raid."
L.ErrAttendeesInvalidRaidBoss = "ID de boss invalide."
L.ErrAttendeesPlayerExists = "Ce joueur est déjà sur la liste des participants au boss."
L.StrAttendeesAddSuccess = "Joueur ajouté aux participants au boss avec succès."

-- ==================== Logger: EditBox Frame ==================== --
L.StrAddEntry = "Nouvelle Entrée"
L.StrEditEntry = "Modifier l'entrée "
L.StrDateEditBox = "Jour/Mois/Année"
-- Error Messages:
L.ErrEditBoxInvalidData   = "Tentative d'ajout d'un élément non valide. Perte possible de données."
L.ErrEditBoxInvalidItem   = "Item invalide: veuillez entrer un lien ou un ID d'item."
L.ErrEditBoxInvalidYear   = "Année invalide : Veuillez entrer une année valide."
L.ErrEditBoxInvalidMonth  = "Mois invalide : veuillez saisir un mois valide."
L.ErrEditBoxInvalidDay    = "Jour invalide : veuillez saisir un jour valide."
L.ErrEditBoxInvalidHour   = "Heure invalide : veuillez entrer une heure valide."
L.ErrEditBoxInvalidMinute = "Minute invalide : veuillez saisir une minute valide. "

-- ==================== Logger: Export Frame ==================== --
L.StrExportBoxTitle = "Exporter l'historique du butin"
L.StrExportFormat   = "Veuillez saisir le format d'exportation:"
L.StrExportBoxHelp   = "Copiez les données ci-dessous et collez-les dans un emplacement externe pour les enregistrer:"

-- ==================== Slash Commands ==================== --
L.StrCmdCommands        = "Sous-commandes acceptables pour |caaf49141/%s|r:"
L.StrCmdToggle          = "affiche ou masque la fenêtre principale"
L.StrCmdConfig          = "affiche ou masque la fenêtre de configuration"
L.StrCmdGrouper         = "accéder aux commandes LFM Spam"
L.StrCmdAchiev          = "recherchez l'ID du haut-fait afin de l'utiliser pour LFM"
L.StrCmdChanges         = "accéder aux commandes des changements MS"
L.StrCmdWarnings        = "accéder aux commandes liées aux avertissements"
L.StrCmdLog             = "accéder aux commandes liées à l'historique"
L.StrCmdLFMStart        = "commence le spam LFM"
L.StrCmdLFMStop         = "arrête le spam LFM"
L.StrCmdChangesDemand   = "demander aux membres du raid de vous envoyer leurs changements MS"
L.StrCmdChangesAnnounce = "annoncer les changements MS au raid"